version: "3.5"

services:

  aria2-ui:

    restart: unless-stopped

    image: wahyd4/aria2-ui:latest

    environment:

      - ENABLE_AUTH=true

      - ARIA2_USER=hello

      - ARIA2_PWD=world

      - DOMAIN=http://toozhao.com

    ports:

      - "80:80"

    volumes:

      - ./data:/data
